name: UI CI/CD Workflow

on:
    push:
        branches:
            - "NA" # prevent action

jobs:
    # pass data to reusable workflow
    configuration:
        name: "Configuration"
        uses: ./.github/workflows/config.yml

    containerizeWebApp:
        name: "Containerize and Push Web App"

        needs: [configuration]
        runs-on: ubuntu-latest
        steps:
            # checkout the repo
            - name: "Checkout Repo"
              uses: actions/checkout@v2

            - name: "Login via Azure CLI"
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_SP_CREDENTIALS }}

            # Variable replacement start (needs to happen after checkout, before build) ##
            - name: Get current date
              id: date
              run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_ENV

            - name: Variable replacement
              uses: microsoft/variable-substitution@v1
              with:
                  files: "./ui/client/src/util/Config.json, ./ui/server/config/serverConfig.json"
              env:
                  buildNumber: ${{ env.date }}-${{ github.run_number }}
                  apimRootUrl: https://${{ fromJson(needs.configuration.outputs.variables).apiManagementServiceName }}.azure-api.net
                  # TODO make negotiate function URL dynamically set, hardcoded for now
                  negotiateFunctionUrl: https://demointegrationfunction.azurewebsites.net/api/signalr_negotiatefunction?
              # Variable replacement end ##

            - name: "Registry Authentication"
              uses: azure/docker-login@v1
              with:
                  login-server: ${{ fromJson(needs.configuration.outputs.variables).containerRegistryName }}.azurecr.io
                  username: ${{ secrets.REGISTRY_USERNAME }}
                  password: ${{ secrets.REGISTRY_PASSWORD }}

            # build with cache
            - name: Set up Docker Buildx
              id: buildx
              # Use the action from the master, as we've seen some inconsistencies with @v1
              # Issue: https://github.com/docker/build-push-action/issues/286
              uses: docker/setup-buildx-action@master
              with:
                  install: true

            - name: Cache Docker layers
              uses: actions/cache@v2
              with:
                  path: /tmp/.buildx-cache
                  # Key is named differently to avoid collision
                  key: ${{ runner.os }}-multi-buildx-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-multi-buildx

            - name: Build production image
              uses: docker/build-push-action@v3
              with:
                  context: ./ui/
                  builder: ${{ steps.buildx.outputs.name }}
                  file: ./ui/Dockerfile.prod
                  # Set the desired build target here
                  target: deploy
                  push: true
                  tags: ${{ fromJson(needs.configuration.outputs.variables).containerRegistryName }}.azurecr.io/${{ fromJson(needs.configuration.outputs.variables).webAppContainerImageName }}:${{ github.sha }}
                  cache-from: type=local,src=/tmp/.buildx-cache
                  # Note the mode=max here
                  # More: https://github.com/moby/buildkit#--export-cache-options
                  # And: https://github.com/docker/buildx#--cache-tonametypetypekeyvalue
                  cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
                  build-args: |
                      "REACT_APP_API_KEY=${{ secrets.API_KEY }}"

            - name: Move cache
              run: |
                  rm -rf /tmp/.buildx-cache
                  mv /tmp/.buildx-cache-new /tmp/.buildx-cache

    # TODO add gate
    deployWebApp:
        name: "Deploy Web Container App"
        needs: [configuration, containerizeWebApp]
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout Repo"
              uses: actions/checkout@v2

            - name: "Login via Azure CLI"
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_SP_CREDENTIALS }}

            - name: "Deploy to Azure Container Instances"
              uses: "azure/aci-deploy@v1"
              with:
                  resource-group: ${{ secrets.RESOURCE_GROUP }}
                  dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
                  image: ${{ fromJson(needs.configuration.outputs.variables).containerRegistryName }}.azurecr.io/${{ fromJson(needs.configuration.outputs.variables).webAppContainerImageName }}:${{ github.sha }}
                  registry-login-server: ${{ fromJson(needs.configuration.outputs.variables).containerRegistryName }}.azurecr.io
                  registry-username: ${{ secrets.REGISTRY_USERNAME }}
                  registry-password: ${{ secrets.REGISTRY_PASSWORD }}
                  name: ${{ fromJson(needs.configuration.outputs.variables).webAppContainerInstanceName }}
                  location: ${{ fromJson(needs.configuration.outputs.variables).location }}

            # ACA IaC pwsh
            - name: "Deploy Container App"
              run: |
                  ./devops/scripts/ui/aca.ps1 ${{ fromJson(needs.configuration.outputs.variables).webAppContainerAppName }} ${{ fromJson(needs.configuration.outputs.variables).webAppContainerAppEnvName }} ${{ fromJson(needs.configuration.outputs.variables).webAppContainerImageName }} ${{ github.sha }}
              shell: pwsh
